In [2]:
import numpy as np
import pandas as pd

In [3]:
X = np.genfromtxt("hw01_data_points.csv", delimiter = ",", dtype = str)
y = np.genfromtxt("hw01_class_labels.csv", delimiter = ",", dtype = int)

In [4]:
def safelog(x):
    return(np.log(x + 1e-100))

In [5]:
a=y_test-1

NameError: name 'y_test' is not defined

In [13]:
y_test

array([2, 2, 1, ..., 2, 2, 2])

In [12]:
a

array([1, 1, 0, ..., 1, 1, 1])

In [6]:
# STEP 3
# first 50000 data points should be included to train
# remaining 44727 data points should be included to test
# should return X_train, y_train, X_test, and y_test
def train_test_split(X, y):
    # your implementation starts below
    X_train = X[:50000]
    y_train = y[:50000]
    X_test = X[50000:]
    y_test = y[50000:]
    # your implementation ends above
    return(X_train, y_train, X_test, y_test)

X_train, y_train, X_test, y_test = train_test_split(X, y)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(50000, 21)
(50000,)
(44727, 21)
(44727,)


In [7]:
# STEP 4
# assuming that there are K classes
# should return a numpy array with shape (K,)
def estimate_prior_probabilities(y):
    # your implementation starts below
    a=y-1
    class_priors = [1-np.mean(a),np.mean(a)]
    # your implementation ends above
    return(class_priors)

class_priors = estimate_prior_probabilities(y_train)
print(class_priors)


[0.04466000000000003, 0.95534]


In [8]:
# STEP 5
# assuming that there are K classes and D features
# should return four numpy arrays with shape (K, D)
#pAcd = probability of having adenine (A) for class c at location d

def estimate_nucleotide_probabilities(X, y):
    # your implementation starts below
    X_1 = X[y==1] 
    X_2 = X[y==2]
    N_1 = len(X_1)
    N_2 = len(X_2)
    
    pAcd=[[],[]]
    
    for d in range(21): 
        pAcd[0].append(sum((X_1[i][d] == 'A') for i in range(len(X[y==1])))/len(X[y==1]))
        pAcd[1].append(sum((X_2[i][d] == 'A') for i in range(len(X[y==2])))/len(X[y==2]))
    
    pCcd=[[],[]]
    for d in range(21): 
        pCcd[0].append(sum((X_1[i][d] == 'C') for i in range(N_1))/N_1)
        pCcd[1].append(sum((X_2[i][d] == 'C') for i in range(N_2))/N_2)
    
    pGcd=[[],[]]
    for d in range(21): 
        pGcd[0].append(sum((X_1[i][d] == 'G') for i in range(N_1))/N_1)
        pGcd[1].append(sum((X_2[i][d] == 'G') for i in range(N_2))/N_2)
    
    pTcd=[[],[]]
    for d in range(21): 
        pTcd[0].append(sum((X_1[i][d] == 'T') for i in range(N_1))/N_1)
        pTcd[1].append(sum((X_2[i][d] == 'T') for i in range(N_2))/N_2)
      
       
    
    # your implementation ends above
    return(pAcd, pCcd, pGcd, pTcd)

pAcd, pCcd, pGcd, pTcd = estimate_nucleotide_probabilities(X_train, y_train)
print(pAcd)
print(pCcd)
print(pGcd)
print(pTcd)

[[0.18674429019256605, 0.17913121361397225, 0.14375279892521273, 0.13390058217644424, 0.11912225705329153, 0.11374832064487236, 0.10523958799820869, 0.10076130765785939, 0.08687863860277653, 0.0761307657859382, 0.06941334527541423, 0.08687863860277653, 0.10120913569189431, 0.09628302731751008, 0.08105687416032244, 0.07926556202418271, 0.23510971786833856, 0.050156739811912224, 0.24540976265114195, 0.23734885803851322, 0.25391849529780564], [0.2683233194464798, 0.2771997404065568, 0.27232189586953337, 0.25808612640525885, 0.2815332761111227, 0.277848724014487, 0.27219628613896624, 0.2608704754328302, 0.2548830782757971, 0.2661879540268386, 0.2738501475914334, 0.26955848179705655, 0.289132664810434, 0.2848619339711516, 0.27694852094542255, 0.2526011681704943, 0.2776603094186363, 0.24981681914292295, 0.28335461720434607, 0.28025624385035697, 0.2927962819519752]]
[[0.2861621137483206, 0.2852664576802508, 0.2857142857142857, 0.2942230183609494, 0.3116883116883117, 0.31751007613076576, 0.310

In [9]:
def calculate_score_values(X, pAcd, pCcd, pGcd, pTcd, class_priors):
    N = X.shape[0]  # Get the number of data points
    K = len(class_priors)  # Get the number of classes
    
    # Initialize a NumPy array to store the score values
    score_values = np.zeros((N, K))
    
    # Iterate over data points
    for i in range(N):
        # Initialize class-specific scores
        class_scores = np.zeros(K)
        
        # Iterate over classes
        for c in range(K):
            # Calculate the score value for class c and data point i
            score = np.log(class_priors[c])  # Initialize with the logarithm of the class prior
            for d in range(21):  # Assuming 21 features
                # Add the logarithm of the probability of the observed nucleotide at location d
                nucleotide = X[i][d]
                if nucleotide == 'A':
                    score += np.log(pAcd[c][d])
                elif nucleotide == 'C':
                    score += np.log(pCcd[c][d])
                elif nucleotide == 'G':
                    score += np.log(pGcd[c][d])
                elif nucleotide == 'T':
                    score += np.log(pTcd[c][d])
            
            # Store the score for class c
            class_scores[c] = score
        
        # Store the class-specific scores for data point i
        score_values[i] = class_scores
    
    return score_values
scores_train = calculate_score_values(X_train, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_train)

scores_test = calculate_score_values(X_test, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_test)

[[-32.29602984 -28.67631805]
 [-35.36510932 -29.06687849]
 [-33.1594779  -28.50829296]
 ...
 [-37.17901126 -29.28659414]
 [-35.6365549  -29.75138901]
 [-28.72885394 -28.68471489]]
[[-31.88852108 -28.73182527]
 [-40.83809258 -29.40573888]
 [-30.6177392  -29.98270774]
 ...
 [-38.49757139 -28.9923932 ]
 [-24.40343148 -29.115305  ]
 [-37.58089652 -28.27846954]]


In [10]:
def calculate_confusion_matrix(y_truth, scores):
    K = scores.shape[1]  # Get the number of classes (K)
    
    # Initialize a NumPy array to store the confusion matrix
    confusion_matrix = np.zeros((K, K), dtype=int)
    
    # Get the predicted class labels by finding the class with the highest score for each data point
    y_pred = np.argmax(scores, axis=1)
    
    # Iterate over data points
    for i in range(len(y_truth)):
        true_class = y_truth[i] - 1  # Assuming class labels are 1-based
        predicted_class = y_pred[i]
        
        # Increment the corresponding cell in the confusion matrix
        confusion_matrix[predicted_class][true_class] += 1
    
    return confusion_matrix
confusion_train = calculate_confusion_matrix(y_train, scores_train)
print(confusion_train)

confusion_test = calculate_confusion_matrix(y_test, scores_test)
print(confusion_test)

[[ 1489  1460]
 [  744 46307]]
[[ 1314  1300]
 [  686 41427]]
